FORMAT: 1A
HOST: https://tbs.fullfabric.com

# FF Intel API v1
The FF Intel API enables you to retrieve data from your FF instance

# Group Classes
Statistics by **Class**


## Classes stats [/api/intel/classes/{id}/states/weekly.json]
### Get stats by week [GET]
+ Response 200 (application/json)

        [{
            "date": "2012-10-22",
            "week": "43",
            "year": "2012",
            "prospect::new": 200,
            "prospect::started_application": 100,
            "applicant::submitted": 50,
            "applicant::admitted_conditionally": 15,
            "applicant::admitted": 5,
            "applicant::accepted": 10,
            "applicant::enrolled": 0,
            "applicant::declined": 5,
            "applicant::rejected": 0,
            "prospects": 300,
            "applicants": 85
        },
        {
            "date": "2012-10-29",
            "week": "44",
            "year": "2012",
            "prospect::new": 250,
            "prospect::started_application": 120,
            "applicant::submitted": 60,
            "applicant::admitted_conditionally": 25,
            "applicant::admitted": 10,
            "applicant::accepted": 15,
            "applicant::enrolled": 0,
            "applicant::declined": 5,
            "applicant::rejected": 0,
            "prospects": 370,
            "applicants": 115
        }]
